vite対応するよ
PeyaPeyaPeyang/HomePage pull request #4
Opened 2022-11-19 18:34 UTC by Potato1682

がんばります

## Cf Pagesでのデプロイ方法

- デプロイ時ルートは`./dist`だよ
- ビルドコマンドは`npm i && npm run build`だよ

## 状況

- いまは`index.html`しか表示できないよ

2022-11-20 18:59 UTC, PeyaPeyaPeyang requested changes

2022-11-20 18:59 UTC, PeyaPeyaPeyang commented on src/pages/contents/artifacts.htm
> +                            >
aタグ等, 1行80字以内で可能な限り1行にしてください.
また, タグの記述内で改行を挟まないでください.(`<a href="hoge>`)

2022-11-20 18:59 UTC, PeyaPeyaPeyang commented on src/pages/contents/contact.htm
> +                <br />
`<br>`の`/`は必要ありません.

2022-11-20 19:08 UTC, Potato1682 commented on src/pages/contents/artifacts.htm
> +                            >
prettierの設定によりこのようなフォーマットになっていたようです。
設定変更により解決しました。

2022-11-20 19:08 UTC, Potato1682 commented on src/pages/contents/contact.htm
> +                <br />
このフォーマットはprettierによってハードコードされており、フォーマット時に自動で追加されるようです。

2022-11-20 19:11 UTC, PeyaPeyaPeyang commented on src/pages/contents/contact.htm
> +                <br />
了解です. 動作や可読性に大幅な影響を与えるものではないため, 解決済みとしてマークします.

2022-11-20 19:16 UTC, PeyaPeyaPeyang commented on package.json
> +    "description": "+ [ぺやんぐのホームページ](https://peya.tokyo)のソースもとい掲示板です.",
ソース自体なのでは..?

2022-11-20 19:33 UTC, Potato1682 commented on package.json
> +    "description": "+ [ぺやんぐのホームページ](https://peya.tokyo)のソースもとい掲示板です.",
READMEの行がinit時にそのままくっついているようです。

2022-11-21 15:32 UTC, PeyaPeyaPeyang approved these changes
LGTM

2022-11-21 15:38 UTC, merged